id = "ferret"
name = "Ferret language support"
description = "Ferret language support for Zed"
version = "0.0.3"
schema_version = 1
authors = ["itsfuad"]
repository = "https://github.com/Ferret-Language/ferret-language-support"

[grammars.ferret]
repository = "https://github.com/Ferret-Language/tree-sitter-ferret"
rev = "main"
